package com.objectcomputing.cubeboard;

import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.core.annotation.Introspected;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import java.util.ArrayList;
import java.util.List;

@Introspected
public class Widget {

    /**
     * The ID used to refer to this widget in the API. It gets generated by the API automatically
     */
    private Long id;

    /**
     * Identifiers what kid of widget is it.
     */
    @NonNull
    @NotBlank
    private String kind;

    /**
     * The widget title, see in the right upper corner
     */
    private String title;

    /**
     * A slug of the dashboard name where this widget lives
     */
    private String dashboard;

    /**
     * Does this widget makes a sound when new data arrive?
     */
    private boolean sound;

    /**
     * Number of columns of the widget on a dashboard.
     */
    private int width;

    /**
     * Number of rows of the widget on a dashboard.
     */
    private int height;

    /**
     * The position of the widget on a dashboard.
     */
    private int row;

    /**
     * The position of the widget on a dashboard.
     */
    private int column;

    @NonNull
    @NotEmpty
    private List<Slot> slots = new ArrayList<>();

    public Widget() {
    }

    public Widget(@NonNull @NotEmpty List<Slot> slots) {
        this.slots = slots;
    }

    @NonNull
    public List<Slot> getSlots() {
        return slots;
    }

    public void setSlots(@NonNull List<Slot> slots) {
        this.slots = slots;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NonNull
    public String getKind() {
        return kind;
    }

    public void setKind(@NonNull String kind) {
        this.kind = kind;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDashboard() {
        return dashboard;
    }

    public void setDashboard(String dashboard) {
        this.dashboard = dashboard;
    }

    public boolean isSound() {
        return sound;
    }

    public void setSound(boolean sound) {
        this.sound = sound;
    }

    public int getWidth() {
        return width;
    }

    public void setWidth(int width) {
        this.width = width;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public int getRow() {
        return row;
    }

    public void setRow(int row) {
        this.row = row;
    }

    public int getColumn() {
        return column;
    }

    public void setColumn(int column) {
        this.column = column;
    }
}
