micronaut:
  application:
    name: cubedashboardpull

# swagger & swagger-ui
---
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
---
micronaut:
  security:
    intercept-url-map:
      - pattern: /swagger/*
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/*
        http-method: GET
        access:
          - isAnonymous()
# cors
---
micronaut:
  server:
    cors:
      enabled: true
# versioning
---
micronaut:
  router:
    versioning:
      enabled: true
---
micronaut:
  security:
    authentication: idtoken
    redirect:
      unauthorized:
        url: '/unauthorized'
      forbidden:
        url: '/denied'
      logout: '/ui'
    oauth2:
      clients:
        cognito:
          client-id: '${OAUTH_CLIENT_ID}'
          client-secret: '${OAUTH_CLIENT_SECRET}'
          openid:
            issuer: '${OAUTH_CLIENT_ISSUER}'
    endpoints:
      logout:
        get-allowed: true
---
app:
  login-redirect: 'http://localhost:5000'
  param-token: 'token'